name: eexily
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio:
  file_picker:
  intl:
  path_provider:
  equatable:
  iconsax_plus:
  flutter_boxicons:
  flutter_screenutil:
  flutter_spinkit:
  cached_network_image:
  flutter_launcher_icons:
  flutter_native_splash:
  timeago:
  shared_preferences:
  flutter_svg:
  socket_io_client:
  go_router:
  flutter_riverpod:
  animated_switcher_plus:
  skeletonizer:
  flutter_staggered_animations:
  flex_color_scheme:
  dropdown_button2:
  animated_snack_bar:
  awesome_notifications:
  flutter_otp_text_field:
  video_player:
  badges:
  emoji_picker_flutter:
  fl_chart:
  faker:
  curved_labeled_navigation_bar:
  easy_stepper:
#  device_preview:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  image_path_android: "assets/images/L11A.png"
  image_path_ios: "assets/images/L11A.png"
  android: true
  ios: true
  adaptive_icon_background: "#0054C2"
  adaptive_icon_foreground: "assets/images/L11A.png"
  min_sdk_android: 29
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  image: "assets/images/L11B.png"
  branding: "assets/images/B11A.png"

  android_12:
    color: "#FFFFFF"
    image: "assets/images/L12A.png"
    branding: "assets/images/B12A.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Black.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/WorkSans-Light.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-SemiBold.ttf
        - asset: assets/fonts/WorkSans-Thin.ttf